services:
  hugo:
    image: floryn90/hugo:0.142.0-ext-alpine
    ports:
     - "1313:1313"
    user: root:root
    volumes:
     - .:/src
    working_dir: /src
    environment:
      - DOCKER=true
    entrypoint: /src/bin/entrypoint.sh
