title: "Gatling Enterprise Self-Hosted documentation"
description: "Gatling Enterprise Self-Hosted documentation"

docSearch:
  indexName: "gatling-self-hosted-legacy"

private: true
product: "Self-Hosted Legacy"
