name: Publish

defaults:
  run:
    shell: bash # Every steps will have a /usr/bin/bash --noprofile --norc -e -o pipefail

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # way to much, but can timeout nonetheless
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout current project
        uses: actions/checkout@v2

      - name: Generate site
        run: |
          docker run \
            --volume "$(pwd)":/src \
            --workdir "/src" \
            --entrypoint "/src/bin/entrypoint.sh" \
            --env DOCKER=true \
            klakegg/hugo:0.87.0-ext-alpine \
            publish
          tar czvf gatlingio.tgz public/

      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: gatlingio-${{ github.workflow }}-${{ github.run_number }}
          path: gatlingio.tgz
          retention-days: 1
