name: Publish

defaults:
  run:
    shell: bash # Every steps will have a /usr/bin/bash --noprofile --norc -e -o pipefail

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 60 # way to much, but can timeout nonetheless
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout current project
        uses: actions/checkout@v2

      - name: Generate site
        run: |
          docker run \
            --volume "$(pwd)":/src \
            --workdir "/src" \
            --entrypoint "/src/bin/entrypoint.sh" \
            --env DOCKER=true \
            klakegg/hugo:0.83.1-ext-alpine \
            publish

      # Note: locally and with optical fiber, the whole step takes roughly 1'30
      # On GitHub Actions, we need more than 30' for the same things!!!
      - name: Mirror site
        env:
          CLEVERCLOUD_USERNAME: ${{ secrets.CLEVERCLOUD_USERNAME }}
          SSHPASS: ${{ secrets.CLEVERCLOUD_PASSWORD }}
          CLEVERCLOUD_BUCKET: ${{ secrets.CLEVERCLOUD_BUCKET }}
        working-directory: ./public
        run: |
          sshpass -e sftp -o StrictHostKeyChecking=no "${CLEVERCLOUD_USERNAME}@${CLEVERCLOUD_BUCKET}" << EOT
          put -r . /
          exit
          EOT
